name: Docker build

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: medai-openai-token-counter:latest
          cache-from: type=registry,ref=medai-openai-token-counter:buildcache
          cache-to: type=registry,ref=medai-openai-token-counter:buildcache,mode=max

      - name: Save image to tarball
        run: docker save -o medai-openai-token-counter.tar medai-openai-token-counter